### ISSUE TITLE
Schema and example are inconsistent

### ISSUE THREAD

**Issue by scouten-adobe** [creator-assertions/training-and-data-mining-assertion#3]
In [§3.2, “Schema and example,”](https://creator-assertions.github.io/training-and-data-mining/1.0/#_schema_and_example) the schema shows a flat list of entries, but the example adds an `entries` map at the top level.

These should be consistent with one another.

**Comment by scouten-adobe** [comment]
My preference: Consider the schema correct and remove the `entries` map from the example.

**Comment by cyraxx** [comment]
I came across this also. The C2PA 1.x variant of this assertion unsurprisingly has the same issue.

One argument against removing the `entries` map is that the (very few) examples of the C2PA 1.x TDM assertion that can be found in the wild seem to have included it. Thus, removing it would make the transition to the CAWG assertion less smooth for claim generators and validators.

**Comment by cyraxx** [comment]
As discussed in today's CAWG meeting: Adobe's existing usage does include the `entries` map, therefore including it in the spec is the preferred way forward.
